theme: jekyll-theme-midnight
title: Going-Ons of Tadukoo
description: Ramblings about my programming, beliefs, videos, and more.
collections:
  changelogs:
    output: true
  guides:
    output: true
  projects:
    output: true
  stories:
    output: true
  story_versions:
    output: true
  story_chapters:
    output: true

defaults:
  - scope:
      path: ""
      type: "changelogs"
    values:
      layout: "changelog"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
      permalink: /story/:name
  - scope:
      path: ""
      type: "story_versions"
    values:
      layout: "story_version"
      permalink: /story/version/:name
  - scope:
      path: ""
      type: "story_chapters"
    values:
      layout: "story_chapter"
      permalink: /story/:categories/:name
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jemoji
  